spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: elsen.hetemov123@gmail.com
    password: ekxbfhlerdmrshbg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true